
import { Inter } from 'next/font/google'
import Provider from '../../Components/Static/Provider'
import '../../Components/Styles/uno.css'
import Header from '../../Components/Static/Header'
import Footer from '../../Components/Static/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Тестовое задание',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html lang="ru">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='anonymous' />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>

  )
}
